version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sis_postgres
    restart: always
    environment:
      POSTGRES_USER: sis
      POSTGRES_PASSWORD: sispassword
      POSTGRES_DB: sis_db
    ports:
      - "5432:5432"
    volumes:
      - sis_pgdata:/var/lib/postgresql/data

volumes:
  sis_pgdata:
